[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "ByQxGL64kgf8tuUxgDYKYTcLUTKcFZRB9tLaK85WJedD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shifu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
